coloca o produto no cart
edimilsoncandidoacct/demoblaze-cypress-e2e pull request #19
Opened 2024-10-30 11:59 UTC by edimilsoncandidoacct

2024-10-30 12:00 UTC, Gersoncd approved these changes

2024-11-05 13:13 UTC, allancostaquality requested changes
Precisa ajustar alguns pontos do código.

2024-11-05 13:13 UTC, allancostaquality commented on cypress/e2e/ui_teste/cart.cy.js
> +    cy.validarImagemCart();
Alterar a validação da imagem para utilizar o método `validarBodyProd`.

2024-11-05 13:13 UTC, allancostaquality commented on cypress/support/commands/ui_commands/cart_commands.js
> +Cypress.Commands.add('validarImagemCart', () => {
Esta command pode ser depreciada e utilizado a `validarBodyProd`.

Quando for validar uma imagem, busque a propriedade e valide o valor dela.

Ela pode existir, mas o valor pode estar errado.
[Itens diferentes no carrinho](https://prnt.sc/QOafBFNIPj5f)

Lembre-se de que a command deve ser genérica, mas a validação precisa ser específica pra não gerar falso positivo.

2024-11-05 13:13 UTC, allancostaquality commented on cypress/support/page_elements/cart_page.js
> +  IMG_CART: '.success > :nth-child(1) > img',
Remover este elemento depreciado, pois a command que a utiliza será depreciada também.

2024-11-07 12:29 UTC, allancostaquality approved these changes

2024-11-07 12:30 UTC, merged